# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # The online documentation for the configuration options is located at
  # https://docs.vagrantup.com

  # Our box
  config.vm.box = "ubuntu/xenial64"

  # Fix weird SSH failures that sometimes happen while provisioning
  config.ssh.keep_alive = true

  # Forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. Accessing
  # "localhost:8000" will access port 8000 on the guest machine.
  config.vm.network :forwarded_port, guest: 8000, host: 8000

  # Custom provisioning and setup script
  config.vm.provision :shell, path: "bootstrap.sh"

  # Customize the amount of memory on the VM:
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

end
